#!/usr/bin/env osascript

on run {theName, theFile}
  set attach to POSIX file theFile
  tell application "Messages"
    set targetBuddy to "rmaghera@ualberta.ca"
    set targetService to id of 1st account whose service type = iMessage
    set theBuddy to participant targetBuddy of account id targetService
    send attach to theBuddy
    send theName
  end tell
end run
