[package]
name = "git-sr"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
clap = { version = "4.4.18", features = ["derive"] }
exec = "0.3.1"
git2 = "0.18.3"
inquire = "0.7.4"

[build-dependencies]
clap = { version = "4.4.18", features = ["derive"] }
clap_complete = "4.4.10"
