name: "Build fruit configuration"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    name: "Build fruit configuration"
    runs-on: macos-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Install Nix
      uses: cachix/install-nix-action@v30
    - name: Load cache configuration
      uses: cachix/cachix-action@v15
      with:
        name: rajan
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Build macOS config
      run: nix build ".#darwinConfigurations.fruit.system" --accept-flake-config
