name: Build custom Nix packages

on:
  push:
    branches:
      - main

jobs:
  build-nix:
    name: Build Nix packages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@v14
      with:
        name: rajan
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#custom-nerdfonts
