name: "Nix CI Dispatch"

on:
  push:
    branches:
      - main

jobs:
  trigger_ci:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            output: x86_64-linux
          - os: macos-latest
            output: aarch64-darwin
          - os: ubuntu-24.04-arm
            output: aarch64-linux
    
    uses: ./.github/workflows/ci.yml
    with:
      os: ${{ matrix.os }}
      output: ${{ matrix.output }}
      
