name: "Nix CI"

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      output:
        required: true
        type: string

jobs:
  build-packages:
    name: Build packages ${{ inputs.output }}
    runs-on: ${{ inputs.os }}
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup cache
        uses: cachix/cachix-action@v17
        with:
          name: rajan
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build packages
        run: nix build .#ciJobs.packages.${{ inputs.output }} --accept-flake-config

  build-systems:
    name: Build systems ${{ inputs.output }}
    needs: build-packages
    runs-on: ${{ inputs.os }}
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup cache
        uses: cachix/cachix-action@v17
        with:
          name: rajan
          skipPush: true

      - name: Build packages
        run: nix build .#ciJobs.systems.${{ inputs.output }} --accept-flake-config
